#!/bin/sh

# PROVIDE: weenas_api
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add these lines to /etc/rc.conf.local or /etc/rc.conf to enable weenas_api:
#
# weenas_api_enable (boolean):
#   Set to YES to enable.
# weenas_api_home (path):
#   /root/weenas by default. Set to the parent path of weenas-api.js.
#
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
. /etc/rc.subr
name="weenas_api"
desc="WeeNAS API"
rcvar=weenas_api_enable
load_rc_config $name
: ${weenas_api_home:=/root/weenas}
command_interpreter=node
command=${weenas_api_home}/${name}.js
command_args="${weenas_api_home}/${name}.js"
pidfile=/var/run/${name}.pid
pid=`pgrep -F /var/run/${name}.pid 2>/dev/null`

start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

weenas_api_start()
{
  echo "Starting ${name}."
  if [ "$pid" == "" ]; then
    ${command_interpreter} ${command_args} >>/var/log/${name}.log 2>&1 &
    pgrep -F /var/run/${name}.pid 2>/dev/null || echo "Start failed."
  else
    echo "${name} is already running as PID: $pid."
  fi
}

weenas_api_status()
{
  echo "Starting ${name}."
  if [ "$pid" != "" ]; then
    echo "${name} is running as PID: $pid."
  else
    echo "${name} is not running."
    return 1
  fi
}

weenas_api_stop()
{
  echo "Starting ${name}."
  if [ "$pid" != "" ]; then
    pkill -F /var/run/${name}.pid
    pgrep -F /var/run/${name}.pid 2>/dev/null && echo "Stop failed."
  else
    echo "${name} is not running."
  fi
}

run_rc_command "$1"
